### ISSUE TITLE
osrm-extract

### ISSUE THREAD

**Issue by tstaa** [ssuluh/osrmnet#19]
Just to let you know the provided osrm-extract crashes on windows 10.
Managed to get it working by updating **libosrm**  with the latest from the their repo, and used the latest extractor.

**Comment by ssuluh** [comment]
@tstaa, the included osrm 5.4.2 works for sure under latest Windows 10.  Couple things to check when it crashes right away:
1.  Check the correct MS C/C++ runtime library is installed.
2.  Make sure you have the temp directory exists, matching what you specified in your .stxxl.txt (default is c:\temp).

Right now osrm.net is compiled against specific version of osrm (5.4.2 currently).  So either you fork the project and rebuild osrm.net using the latest osrm yourself, or if you decide to use osrm as is from nuget, you must extract your data files using the included 5.4.2. AFAIK, OSRM **does not** guaranteed the resulting extracted file compatibility in between version, it may work or may not (worse if it's data corruption without you knowing about it).
