### ISSUE TITLE
return json string

### ISSUE THREAD

**Issue by tstaa** [ssuluh/osrmnet#20]
I'm very sorry to bother you, perhaps this is a bit generic question but been trying to resolve it for hours and googling did not help.
All I want is to create a function that returns the json object as a string, this is what I have so far:

OSRM.h
`System::String^ Route(RouteParameters^ routeParameters);`

OSRM.cpp
```
System::String^ osrmnet::Osrm::Route(osrmnet::RouteParameters^ routeParameters)
{
	osrm::util::json::Object jsonResult;

	try
	{
		osrmEngine->Route(*routeParameters->InnerObject(), jsonResult);

		//CONVERT jsonRsult TO STRING AND RETURN
	}
	catch (const std::exception&)
	{
		return "";
	}
}
```

As you can see, I'm basically struggling to convert jsonResult to string and return it.
I'll be manipulating the the contents in my client application.
Sorry again, C++ is really not my area, just like this library very much
Thanks

**Comment by ssuluh** [comment]
@tstaa, I'm guessing you're trying to get the Steps ?  If you are, you could:
1.  Wait for me to push an update.  I think I'm almost done, all I have to do is to test them.  So far the ETA for Steps support is like this weekend.
2.  If you want to manipulate the jsonResult directly, I would look into osrm::util::json inside the osrm project itself.  Unfortunately it's all C++ code, and I'm sure there's a way to do 'ToString()' equivalent in there.

I was considering returning String^ as a result before, but that's kinda defeat the purpose of this library which is strong typing on all input and output params.

**Comment by tstaa** [comment]
Thanks for your reply,
I've just spent couple of more hours looking at the C++ code trying to get the string, didn't get anywhere, so I guess I'm just gonna have to wait for your implementation of the steps.
However, I think it would be nice to have an additional function that returns the json string.

Thanks for your work.

**Comment by ssuluh** [comment]
@tstaa , as far as returning String goes let me think about it some more. The same reason this project is started because the C++ library already returning a string to begin with.  This way .NET client that want to use OSRM.net doesn't have to parse the json, everything is strongly typed.  But if the demand to return the raw string is there then I will consider it.

**Comment by tstaa** [comment]
I see your point, however besides the strongly typed results, running it directly without the web server is another major point of this project I think, so just the ability to do that might be enough in some cases, hence is my point here. in the end it's completely up to you. thanks again

**Comment by ssuluh** [comment]
Yes sir you're correct. Libosrm which is the library where the osrm server is built on, actually is pretty fast and efficient library, the only thing is the output is actually json string.  The only thing I wish is they actually return structure/class this way at the lower layer it's more efficient and let the string conversion to json is done on the layer above it in .NET side (like use Newtonsoft for example).  (BTW, I almost done with Steps, just trying to do a little more testing before I commit and update).

**Comment by ssuluh** [comment]
@tstaa, do you mind help me QA with steps=true? It may take a while to show up in nuget, but it should be version 0.1.0.34. Anything you find, please feel free to create new issue..
