### ISSUE TITLE
Upgrade Project to VS2017

### ISSUE THREAD

**Issue by ssuluh** [ssuluh/osrmnet#30]
- Update c++ toolset and test project under vs2017.
- Update Appveyor build image

**Comment by ssuluh** [comment]
Item is on hold until boost is fully supported in 2017

**Comment by 03July** [comment]
Hello,

Now boost is supported in VS2017, could you please update the project for VS2017 and use the latest release build : http://build.project-osrm.org/ ?

Kind regards,
Daniel

**Comment by ssuluh** [comment]
Addressed by #27
