### ISSUE TITLE
Cannot open include file: 'boost/filesystem.hpp': No such file or directory

### ISSUE THREAD

**Issue by a6datta** [ssuluh/osrmnet#31]
Hi,
I was unable to build osrmnet in VS2015. I am looking forward to release version, very excited. I am currently using Route() through web server. I use returned Geometry to draw route path on a map. Once I started writing a similar program myself but did not have enough experience doing it on my own. I was following this tutorial. 
https://www.codeproject.com/Articles/165383/Integrating-an-unmanaged-C-lib-with-C

**Comment by ssuluh** [comment]
a6datta I apologize for not responding, I've been out for the last 3 weeks.  Please try it with running build.ps1 to get the project dependencies.  You only need to do this one time (or a major version of osrm is included).  I'll update the readme.md with this information.

**Comment by ssuluh** [comment]
@a6datta , since it's been a while I assume you solved the issue. Feel free to reopen this if it's not the case.
