### ISSUE TITLE
osrmnet.OsrmException: "Invalid file paths given!"

### ISSUE THREAD

**Issue by linuzer** [ssuluh/osrmnet#33]
I had it already running with an earlier version some time ago. Now I upgraded to the current release and get constantly the above runtime-error. I tried already several things, but I cannot figure out what I'm doing wrong. I use the following code:

```
      Dim objOSSRM As osrmnet.Osrm = Nothing
      If objOSSRM Is Nothing Then
         osrmEngineConfig = New osrmnet.EngineConfig
         osrmEngineConfig.StorageConfig = "C:\usr\OSRM\data\us-west-latest.osrm"
         osrmEngineConfig.UseSharedMemory = False
         objOSSRM = New osrmnet.Osrm(osrmEngineConfig)
      End If
```
The path looks like this:
```
C:\usr\OSRM\data>dir
 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer: AE7A-767C

 Verzeichnis von C:\usr\OSRM\data

24.04.2017  18:02    <DIR>          .
24.04.2017  18:02    <DIR>          ..
24.04.2017  16:10     1.695.726.639 us-west-latest.osm.pbf
24.04.2017  17:37     1.942.794.140 us-west-latest.osrm
24.04.2017  17:44       406.432.272 us-west-latest.osrm.cnbg
24.04.2017  17:39       114.925.728 us-west-latest.osrm.cnbg_to_ebg
24.04.2017  18:02                16 us-west-latest.osrm.core
24.04.2017  17:46            66.056 us-west-latest.osrm.datasource_names
24.04.2017  17:45       548.747.260 us-west-latest.osrm.ebg
24.04.2017  17:44       438.997.864 us-west-latest.osrm.edges
24.04.2017  17:44        55.134.988 us-west-latest.osrm.enw
24.04.2017  17:45     1.379.463.168 us-west-latest.osrm.fileIndex
24.04.2017  17:44       978.813.076 us-west-latest.osrm.geometry
24.04.2017  18:02     1.511.739.924 us-west-latest.osrm.hsgr
24.04.2017  17:44       146.011.328 us-west-latest.osrm.icd
24.04.2017  18:02                16 us-west-latest.osrm.level
24.04.2017  17:37        11.392.364 us-west-latest.osrm.names
24.04.2017  17:45       441.814.632 us-west-latest.osrm.nodes
24.04.2017  17:37               296 us-west-latest.osrm.properties
24.04.2017  17:45         1.411.944 us-west-latest.osrm.ramIndex
24.04.2017  17:37           725.360 us-west-latest.osrm.restrictions
24.04.2017  17:37                28 us-west-latest.osrm.timestamp
24.04.2017  17:44             5.556 us-west-latest.osrm.tld
24.04.2017  17:44            10.140 us-west-latest.osrm.tls
24.04.2017  17:44        54.874.740 us-west-latest.osrm.turn_duration_penalties
24.04.2017  17:44       658.496.688 us-west-latest.osrm.turn_penalties_index
24.04.2017  17:44        54.874.740 us-west-latest.osrm.turn_weight_penalties
              25 Datei(en), 10.442.458.963 Bytes
               2 Verzeichnis(se), 100.225.077.248 Bytes frei
```
Many thanks for help!

**Comment by ssuluh** [comment]
Hi @linuzer , how do you generate that osrm file ? (Version of the osrm utility you're using ?)  osrmnet is currently linked to osrm version 5.4.2.

**Comment by linuzer** [comment]
Ah, yes, I think that is the problem ... I forgot, the version has to match exactly. 
But now I have trouble to (re)compile the 5.4.2 version. On the result it tells me always
```
osrm-extract -v
version 5.4.0
```
...and I keep getting the fingerprint error.

Is it not possible to put the linked binaries into the release?

**Comment by ssuluh** [comment]
The osrm dependencies are too big for git to be checked in without eventually leads into performance problem.  But if you clone this repository and build it locally (instruction in readme.md), the script will pull the right osrm version locally and it included the right osrm-extract etc.  The build.ps1 scripts is what fetch the dependencies locally.

**Comment by linuzer** [comment]
The point I wanted to make is, if you have compiled everything, you need to prepare the data with the exact same OSRM binaries, but these binaries are nowhere available online - at least there is nowhere a reference to it. The corrosponding zip is far less than 10 MB and I thought it would not be a big issue to put it in a subfolder of this repo.

Now with your last hint I discovered, that the build.ps1 in fact does download it, so it can be found in the subfolder .\src\osrm.net\libosrm\redist\osrm_5.4.2.zip. The script downloads it from [https://s3.amazonaws.com/osrmnet/5.4.2/libosrm.zip](https://s3.amazonaws.com/osrmnet/5.4.2/libosrm.zip) so in fact it is online available. I think it would be a priceless help for any user to have these two information directly in the Readme.

So, I was able to prepare the data with this binary version, the file is loading up, but when I try to get a routing, the route()-call crashes with the runtime exception 
`System.Runtime.InteropServices.SEHException: "An external component has generated an exception."`
Unfortunately there is no further information included in the exception.
The very same coordinates sent directly to the web-api of osrm-routed returns the expected result.

Is there a way to find out what's going on?

**Comment by ssuluh** [comment]
@linuzer, this is what I had originally, check in the dependencies (including the tools). Git get slower when we have lots of binaries files overtime.  Github git-lfs implementation does not help either (cost too much money for oss project like this). I also don't want necessarily advertise that s3 endpoints (amazon bandwidth cost and may be moved in the future).  If you look at the osrm project, they do the same thing by offloading 3rd party offsite somewhere since we don't have package manager in c++ like nuget.
 
To get the matching tools the best thing for now is what you just did, run that script one time and keep the tools locally.  I'll update the readme for the build step and the tools for everyone.

As far as your error goes, without seeing it in person, I can only offer generic advice.  Do you have all the necessary prerequisite to load that library (right version of vc runtime library comes to mind)? Check also the configs, paths, etc. Refers to: [osrm windows compilation](https://github.com/Project-OSRM/osrm-backend/wiki/Windows-Compilation.)

Since this project is guarded by unit test, and it passes on the appveyor server so I think it is your environment.  You can see there how I load the osrmnet and invoke the Route() method.

**Comment by linuzer** [comment]
Thanks for the help, I got it finally.
