### ISSUE TITLE
Nuget package does not work with IIS or IIS Express

### ISSUE THREAD

**Issue by benjamin-miller** [ssuluh/osrmnet#42]
When upgrading from version 0.1.0.55-pre to 1.0.0.4-pre I found that IIS hosted applications to fail with the following exception:

> Could not load file or assembly 'osrm.net.DLL' or one of its dependencies. The specified module could not be found.

Investigation showed that tbb.dll and tbbmalloc.dll were no longer being loaded, however adding them to c:\windows\system32\inetsvr would allow the application to find them and resolve the error.  The issue is related to IIS only copying managed assemblies to its temporary directory.  Normal applications have no issue loading the assembly since they check their working directory for any additional dependencies.

To replicate the issue do the following:

- Create a basic IIS hosted application. I specifically used an OWIN based WebAPI application hosted in IIS.
- Include the OSRM.Net 1.0.0.4-pre nuget package.
- Open an endpoint into the application.  The endpoint doesn't even need to be valid, it just needs to call into the application so IIS begins loading assemblies.

**Comment by ssuluh** [comment]
Ben, I am not sure if this is something that can be addressed by nuget itself (or even if it's doable, it'll be worth doing). It's either you turn off the shadow copying in IIS or make it part of your deployment strategy of your app.
