### ISSUE TITLE
Upgrade to OSRM 5.15.0

### ISSUE THREAD

**Issue by bdaunt** [ssuluh/osrmnet#43]
The current OSRM-Backend redistributables are v5.15.0 and return an error when configuring the engine.

**Comment by ssuluh** [comment]
Hello @bdaunt I'm going to work on the upgrade but 5.15 is not release yet, so do you want to wait until 5.15 is released or I can release osrmnet with latest of 5.14 ?

**Comment by ssuluh** [comment]
5.15 is not released yet, so I'm releasing it with 5.14.2
