### ISSUE TITLE
[Question] Is an instance of OSRM object is thread safety?

### ISSUE THREAD

**Issue by ifle** [ssuluh/osrmnet#48]
What is the right way to use the instance of OSRM object? Is it can be used as singleton?

**Comment by ssuluh** [comment]
I have to investigate it fully, but I assume it is not safe. The .net side code should be safe, but I'm not so sure about the unmanaged libosrm part.

**Comment by ssuluh** [comment]
I posted this question in osrm project ([Issue 4966](https://github.com/Project-OSRM/osrm-backend/issues/4966))

**Comment by ssuluh** [comment]
@ifle they said it's thread safe.
