### ISSUE TITLE
Is osrmnet production ready?

### ISSUE THREAD

**Issue by ifle** [ssuluh/osrmnet#50]
Do you know is someone use it in production?

**Comment by ssuluh** [comment]
I'm not sure. It'll be nice to find that out, but I look up nuget.org latest version is downloaded 73 times. I know it doesn't tell definitely how it's used, but hopefully there's at least one that using it in production. But I need help in increasing the unit test coverage as it wasn't develop tdd way.

**Comment by swadhin-** [comment]
The issue with osrmnet is there is no documentation provided on how to connect osrmnet with osrm. If something goes wrong it throws a generic exception and then you are left with no choice but to go through the entire library or see issue log on github.

There is a major issue where if the versions do not match it does not build.

**Comment by ifle** [comment]
@swadhin- Do you use it on production?

**Comment by swadhin-** [comment]
I stopped using it because of the versioning issue

**Comment by ifle** [comment]
How to you use osrm on windows?

**Comment by swadhin-** [comment]
There are pre-built versions.
1. https://github.com/Project-OSRM/osrm-backend/wiki/Windows-Compilation
2. http://build.project-osrm.org

But these versions are not supported by osrmnet.

**Comment by ifle** [comment]
Thanks. the latest version built 1Feb 2018. OSRM team official does not support windows. There is also nodejs wrapper, but it also does not support windows

**Comment by ssuluh** [comment]
@ifle @swadhin- , sorry I've been swamped recently with other project, but what I can do I can work on syncing up with the latest version of osrm and release a version. I'll see if I can work a better documentation for user to build it themselves.  For the most part you have to build osrm locally first before you can use the output of that build to build osrmnet.

**Comment by ifle** [comment]
Thanks @ssuluh. Do you have a lot experiences with osrm builds on windows, maybe can you contribute to osrm project to support nodejs wrapper for windows? 
Unfortunately the osrm team does not support the nodejs build for windows.

**Comment by ifle** [comment]
> 'll see if I can work a better documentation for user to build it themselves. For the most part you have to build osrm locally first before you can use the output of that build to build osrmnet.

@ssuluh That will be very helpful. I tried build osrm locally without any success.
```
 Failed to run MSBuild command:

    C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 14.0.23107.0
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 1/1/2019 15:18:18.
    Project "D:\Dev\GitHub\osrm-backend\build\CMakeFiles\3.13.2\VCTargetsPath.vcxproj" on node 1 (default targets).
    D:\Dev\GitHub\osrm-backend\build\CMakeFiles\3.13.2\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
    Done Building Project "D:\Dev\GitHub\osrm-backend\build\CMakeFiles\3.13.2\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "D:\Dev\GitHub\osrm-backend\build\CMakeFiles\3.13.2\VCTargetsPath.vcxproj" (default target) (1) ->
      D:\Dev\GitHub\osrm-backend\build\CMakeFiles\3.13.2\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

        0 Warning(s)
        1 Error(s)

```
