### ISSUE TITLE
Version 5.22?

### ISSUE THREAD

**Issue by Stan92** [ssuluh/osrmnet#55]
Hi,
Is it possible get the version 5.18 of the osrm tools?

Using the current version, the app failed saying 
xxxxx.osrm.cells prepared with OSRM 5.22.0 but this is v5.18.0 

thanks for your help

**Comment by Stan92** [comment]
I've finally downloaded the right branch.. everything is ok.

**Comment by ssuluh** [comment]
Glad you figured it out. If you build locally, there should be a zip file inside src\osrmnet\libosrm\redist that contains the matching osrm library and tools.
