### ISSUE TITLE
Upgrade to the latest version?

### ISSUE THREAD

**Issue by Stan92** [ssuluh/osrmnet#56]
Hi,
Do you have any roadmap about the upgrade to the latest version of OSRM (5.2x)?
Thanks.

**Comment by ssuluh** [comment]
Yes, I'm working on updating it to 5.22.0. Sorry took a while for me to get to it.

**Comment by ssuluh** [comment]
Completed upgrade to 5.22. See PR #57

**Comment by ssuluh** [comment]
@Stan92 , if you go to nuget, you should be able to use [osrmnet 1.0.0.20](https://www.nuget.org/packages/osrmnet/1.0.0.20). This version is precompiled for 5.22 osrm.
