### ISSUE TITLE
Can build this project with dotnet core ?

### ISSUE THREAD

**Issue by Longnt1208** [ssuluh/osrmnet#59]
Hi ssuluh,

I installed you lib by nuget and I have warning that this lib only support .net framework. How can build your lib with .net core support ?

**Comment by ssuluh** [comment]
It may not be possible. The c++ wrapper is written with c++/cli which afaik is not supported in .net core. You may have wrapped the osrm directly with tools like  https://github.com/mono/CppSharp.

**Comment by Longnt1208** [comment]
I will try, thank you.
