### ISSUE TITLE
.NET Core 3.1 Support

### ISSUE THREAD

**Issue by tstaa** [ssuluh/osrmnet#61]
.NET Core 3.1 Preview 1 (Visual Studio 2019 - 16.4.0 Preview 2) now supports .NET Core CLR Library.

I tried to modify the project myself, I couldn't get it to work, I'm not very familiar with C++ or C++/CLI project systems.

**Comment by ssuluh** [comment]
@tstaa, I'll take a look this weekend

**Comment by Stan92** [comment]
> @tstaa, I'll take a look this weekend

Hi, still in progress? :-)

**Comment by ssuluh** [comment]
I'm afraid so been out of the country and busy. I'll try to do it next week, code is reviewed but the CD pipeline may have to be revisited to be able to publish it correctly.

**Comment by ssuluh** [comment]
I know it's been a long time, but today I have significant progress. New revamped build system utilizing git submodule that link to the osrm-backend project, .net core 3.1 re-target for main and test project. Known limitation it's still 64 bit Windows OS only. 

What's left to be done:

- [ ] Rebuild the AppVeyor Pipeline
- [ ] Have Docker build the osrm-backend portion
- [ ] Nuget package probably need rework for targetting core 3.1

**Comment by ssuluh** [comment]
> I know it's been a long time, but today I have significant progress. New revamped build system utilizing git submodule that link to the osrm-backend project, .net core 3.1 re-target for main and test project. Known limitation it's still 64 bit Windows OS only.
> 
> What's left to be done:
> 
> * [ ]  Rebuild the AppVeyor Pipeline
> * [ ]  Have Docker build the osrm-backend portion
> * [ ]  Nuget package probably need rework for targetting core 3.1

I got blocked by the build tools:
https://github.com/MicrosoftDocs/visualstudio-docs/issues/4915

**Comment by suou-ryuu** [comment]
@ssuluh Hey

I tried cloning the repo and building the `netcore31-upgrade` branch locally but `Boost` was unavailable (I didn't have it installed). I tried installing it but ran into a host of issues that have taken up most of my day.
I was wondering if you could send me a copy of the built output to include in a dotnet core app?
I ask as we need it fairly urgently in my company right now.

Thanks

**Comment by ssuluh** [comment]
> @ssuluh Hey
> 
> I tried cloning the repo and building the `netcore31-upgrade` branch locally but `Boost` was unavailable (I didn't have it installed). I tried installing it but ran into a host of issues that have taken up most of my day.
> I was wondering if you could send me a copy of the built output to include in a dotnet core app?
> I ask as we need it fairly urgently in my company right now.
> 
> Thanks

That branch is still work in progress. But I can tell you what's the plan. There's a git submodule in there that is set to point to the 5.22 version of osrm-backend. You have to build that project first (to build locally there should be a file build-local.bat, but if you run into trouble there's documentation in their website for building under windows). After this is good, then osrmnet can be build on top of it.

**Comment by suou-ryuu** [comment]
Thank you for the quick response. :)
I'll give your suggestion a try tomorrow

**Comment by ssuluh** [comment]
At the moment the main project of osrm build is no longer working. I'm blocked because of it.
https://github.com/Project-OSRM/osrm-backend/issues/5718

**Comment by suou-ryuu** [comment]
I'm really sorry for the late reply, the current climate has made things too crazy to be able to keep up with.
I only just managed to get to trying a local build today (thankfully, I still have a copy of the osrm-backend binaries and the master branch from ~a month ago) and encountered the following errors when running the build.ps1 file:

For the osrrm,net project:
```
C: \ Program Files (x86) \ Microsoft Visual Studio \ 2017 \ Community \ Common7 \ IDE \ VC \ VCTargets \ Microsoft.Cpp.Platform.targets (67,5): error
MSB8020: No build tools found for v142 (Platform Toolset = 'v142'). To build using the v142 build tools, install the v142 build tools. Alternatively, select the Project menu or
You can also right-click the solution and select Retarget Solution to upgrade to the current Visual Studio Tools.
```

For the osrm.net.test project:
```
Microsoft.NET.TargetFrameworkInference.targets (137,5): error NET
SDK1045: The current .NET SDK does not support targeted .NET Core 3.1. Target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.1.
```

Any idea how to resolve these?
Or, if you have a working netcore build of the solution that would work. I only need to drop it in a project so we can migrate away from .NET framework.

Sorry again for the late reply.

**Comment by ssuluh** [comment]
@suou-ryuu , it seems that you're missing the appropriate sdks. Make sure you have the appropriate c++ sdk for the first error and the .net core sdk for the 2nd error.

**Comment by suou-ryuu** [comment]
For some reason the v142 build tools are not available for VS2017 (which the build is looking for). Upgrading cake to the latest version allowed me to target VS2019 which does have the v142 build tools.
However I eventually got to an error where osrm.lib can't be found, and when running the backend build I get a 403 error when it tries to download an osrm-deps zip file.

If you happen to have an old dotnetcore build available could you perhaps host it somewhere, e.g. Google drive, for me to download. We're currently in the process of migrating a bunch of stuff away from .NET Framework and the project that relies on this is the last thing that needs migrating.

**Comment by ssuluh** [comment]
> However I eventually got to an error where osrm.lib can't be found, and when running the backend build I get a 403 error when it tries to download an osrm-deps zip file.
> 
Yes, so this is where I was stopped. I created issues in their repo, see my post above:  #Project-OSRM/osrm-backend#5718

**Comment by ssuluh** [comment]
@suou-ryuu , I just published new version in nuget. Do you mind testing this and let me know ? Thanks.

**Comment by suou-ryuu** [comment]
@ssuluh Thank you for publishing a new version, I really appreciate it :)

Unfortunately, after downloading and trying to run a solution I got the following error:
```
System.BadImageFormatException
  HResult = 0x8007000B
  Message = Could not load file or assembly 'osrm.net, Version = 3.1.0.27, Culture = neutral, PublicKeyToken = null'. You tried to load a program in the wrong format.
```

This is in a netcoreapp3.1, and I tried both x64 and x86 platforms but in both cases got the above error.

**Comment by ssuluh** [comment]
> @ssuluh Thank you for publishing a new version, I really appreciate it :)
> 
> Unfortunately, after downloading and trying to run a solution I got the following error:
> 
> ```
> System.BadImageFormatException
>   HResult = 0x8007000B
>   Message = Could not load file or assembly 'osrm.net, Version = 3.1.0.27, Culture = neutral, PublicKeyToken = null'. You tried to load a program in the wrong format.
> ```
> 
> This is in a netcoreapp3.1, and I tried both x64 and x86 platforms but in both cases got the above error.

This is because of your .net process is running in 32 bit (the platform has nothing to do with it, you can still run 32 bit in 64 bit platforms) . Check some of the past issues: https://github.com/osrmnet/osrmnet/issues?q=BadImageFormatException+

**Comment by suou-ryuu** [comment]
As I said, the error occurred when the project was set to run in either x64 or x86 platform.
I'll try again tomorrow to be sure but the project was originally x64 and I only tried x86 out of curiosity

**Comment by ssuluh** [comment]
> As I said, the error occurred when the project was set to run in either x64 or x86 platform.
> I'll try again tomorrow to be sure but the project was originally x64 and I only tried x86 out of curiosity
@suou-ryuu ,  have you any luck in resolving this ?

**Comment by ssuluh** [comment]
@suou-ryuu , sorry about this issues.  But it should fixed now, please download the latest from nuget. https://github.com/osrmnet/osrmnet/issues/71

**Comment by suou-ryuu** [comment]
@ssuluh I'm really sorry for the delay. I've been really busy with work this week, trying to push out a search service. I've just had another look at this and tried the latest version you kindly made available (3.1.0.29) and I'm experiencing the same error. For reference, here is the project file (I've excluded included code files includes as they are noise that aren't related to this issue):

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <OtherFlags>
      <!-- warn on unused -->$(OtherFlags) --warnon:1182
    </OtherFlags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="4.6.2" />
    <PackageReference Include="osrmnet" Version="3.1.0.29" />
  </ItemGroup>

</Project>
```

**Comment by ssuluh** [comment]
@suou-ryuu , sorry again about the nuget mishaps. Please retry it again with 3.1.0.30 since 29 still have issue with not copying all the dependencies at the right location. The only other thing (not sure if this will be a different problem altogether) is that the c++ portion of the osrmnet is compiled using Win10 sdk, to be safe your RuntimeIdentifier has to be win10-x64. But this means you need to run this in Windows 10 or Windows Server 2016 and up.

**Comment by suou-ryuu** [comment]
@ssuluh Apologies for the delay. I've been struggling with internet for the past 2 days (my ISP are having issues during the state of emergency). I'll do my best to try it out tomorrow and get back to you, although it may be as late as Friday. Sorry :(

**Comment by suou-ryuu** [comment]
@ssuluh I'm very sorry for the delayed response. I'm no longer seeing the `BadImageFormatException` but I'm now getting this error:
```
Required files are missing, cannot continue.  Have all the pre-processing steps been run?'
```

It's not too informative so I'm not sure which files it's referring to. Any ideas?

**Comment by ssuluh** [comment]
@suou-ryuu , this is something to do with your osrm data. Did you preprocess the file correctly, specify correct algorithm ? This could be so many other things, but it is outside osrmnet. Please refer to [osrm documentation](https://github.com/Project-OSRM/osrm-backend/wiki) in particular how you prepare the data files. I'm closing this issues as I had confirmation from others it's working.
