### ISSUE TITLE
how to upgrade lib to osrm v5.24

### ISSUE THREAD

**Issue by NguyenSen** [ssuluh/osrmnet#74]
you can support upgrade lib osrm v5.24

**Comment by r-work** [comment]
Wondering the same, this would be great.

**Comment by r-work** [comment]
Wondering the same, that would be great.

**Comment by ssuluh** [comment]
Thank you for your interest in osrm.net. I have to look into it again as the last time we had issue building osrm from the parent project for Windows which prevent the upgrade work

**Comment by dantey89** [comment]
+1 for feature request

**Comment by NguyenSen** [comment]
I try it and success for rebuild with osrm5.24
Thanks @ssuluh
