### ISSUE TITLE
Error when using nuget package 

### ISSUE THREAD

**Issue by a6datta** [ssuluh/osrmnet#75]
@ssuluh 
I have downloaded the latest (2018) pre built windows binary from http://build.project-osrm.org/ and extracted the pbf files using these commands.
osrm-extract great-britain-latest.osm.pbf
osrm-partition great-britain-latest.osrm
osrm-customize great-britain-latest.osrm

When I use osrmnet nuget package, it doesn't work.
```
using (Osrm osrm = new Osrm(new EngineConfig() {StorageConfig= AppDomain.CurrentDomain.BaseDirectory + @"osrm_new\great-britain-latest.osrm", Algorithm=Algorithm.MLD, UseSharedMemory=false })) 
            {
                RouteResult routeResult;
                var result = osrm.Route(new RouteParameters()
                {
                    Coordinates = new List<Coordinate>()
                    {
                        new Coordinate(51.559510, -0.132860),
                        new Coordinate(51.461280, -0.020340)
                    },
                }, out routeResult);

                Debug.WriteLine(routeResult.Code);
            }
```

I get this error
Required files are missing, cannot continue.  Have all the pre-processing steps been run?

What am I doing wrong?

**Comment by a6datta** [comment]
The library support osrm ver 5.22 but I think the pre-built ver is 5.16.

**Comment by ssuluh** [comment]
@a6datta, osrm project no longer maintain windows build. If you want the latest that they have,  you have to build it yourself.  As of right now, osrmnet only goes up to 5.22.  If you want 5.22, you need to run build.ps1 to build it locally and the 5.22 library will be downloaded and it should be in .\osrmnet\src\osrm.net\libosrm\redist

**Comment by a6datta** [comment]
@ssuluh 

Is there any issue with 5.22. Because when I build and run, there is an error. However the pre build binary 5.16 works fine. 

C:\Users\datta\source\repos\WinFormsApp2\WinFormsApp2\bin\Release\netcoreapp3.1>osrm-extract great-britain-latest.osm.pbf
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons←[0m
[info] Using script profiles/car.lua←[0m
[info] Input file: great-britain-latest.osm.pbf←[0m
[info] Profile: car.lua←[0m
[info] Threads: 16←[0m
[info] Parsing in progress..←[0m
[info] input file generated by Osmium (http://wiki.openstreetmap.org/wiki/Osmium)←[0m
[info] timestamp: 2016-12-14T20:28:02Z←[0m
[info] Using profile api version 0←[0m
[info] Found no turn restriction tags←[0m
[info] Parse relations ...←[0m
[info] Parse ways and nodes ...←[0m
[info] Using profile api version 0←[0m
[info] Using profile api version 0←[0m
[info] Using profile api version 0←[0m
[info] Using profile api version 0←[0m
[info] Using profile api version 0←[0m
[info] Using profile api version 0←[0m
[info] Using profile api version 0←[0m
[info] Using profile api version 0←[0m
[info] Using profile api version 0←[0m
[info] Using profile api version 0←[0m
[info] Using profile api version 0←[0m
[info] Using profile api version 0←[0m
[info] Using profile api version 0←[0m
[info] Using profile api version 0←[0m
[info] Using profile api version 0←[0m
[info] Parsing finished after 36.2 seconds←[0m
[info] Raw input contains 87551631 nodes, 11048311 ways, and 0 relations, 10229 restrictions←[0m
[info] Sorting used nodes        ... ok, after 0.149666s←[0m
[info] Erasing duplicate nodes   ... ok, after 0.040852s←[0m
[info] Sorting all nodes         ... ok, after 0.10986s←[0m
[info] Building node id map      ... ok, after 0.158817s←[0m
[info] Confirming/Writing used nodes     ... ok, after 0.975952s←[0m
[info] Writing barrier nodes     ... ok, after 0s←[0m
[info] Writing traffic light nodes     ... ok, after 0s←[0m
[info] Processed 14073957 nodes←[0m
[info] Sorting edges by start    ... ok, after 1.23511s←[0m
[info] Setting start coords      ... ok, after 0.941805s←[0m
[info] Sorting edges by target   ... ok, after 1.16115s←[0m
[info] Computing edge weights    ... ok, after 2.2133s←[0m
[info] Sorting edges by renumbered start ... ok, after 1.21157s←[0m
[info] Writing used edges       ... ok, after 0.522184s -- Processed 14669062 edges←[0m
[info] Writing way meta-data     ... ok, after 0.007963s -- Metadata contains << 2296291 entries.←[0m
[info] Sorting used ways         ... ok, after 0.007255s←[0m
[info] Collecting start/end information on 0 maneuver overrides...ok, after 0.012236s←[0m
[info] Collecting start/end information on 0 maneuver overrides...ok, after 0s←[0m
[info] Collecting start/end information on 10229 restrictions...ok, after 0.04284s←[0m
[info] Collecting start/end information on 10229 restrictions...ok, after 0.009336s←[0m
[info] writing street name index ... ok, after 0.022248s←[0m
[info] extraction finished after 45.4242s←[0m
[info] Generating edge-expanded graph representation←[0m
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%←[0m
[info] Node compression ratio: 0.249188←[0m
[info] Edge compression ratio: 0.279537←[0m
[info]  graph compression removed 1910926 annotations of 2296291 in 4.47987 seconds←[0m
[info] Find segregated edges in node-based graph ...←[0m
[info] ok, after 11.0382s←[0m
[info] Segregated edges count = 27803←[0m
[info] Writing nodes for nodes-based and edges-based graphs ...←[0m
[info] Geometry successfully removed:
  compressed edges: 8199900
  compressed geometries: 29373010
  longest chain length: 552
  cmpr ratio: 0.279164
  avg chain length: 3.58212←[0m
[info] Generating edge expanded nodes ... ←[0m
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%←[0m
[info] Expanding via-way turn restrictions ... ←[0m
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%←[0m
[info] Generated 7784253 nodes (333 of which are duplicates)  and 14666821 segments in edge-expanded graph←[0m
[info] Generating edge-expanded edges ←[0m
[info] . 10% . 20% .←[33m[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 3883647, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=57.54519&mlon=-4.002806←[0m
 30% . 40% . 50% ←[33m[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 7650413, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=50.811217&mlon=-1.094881←[0m
. 60% . 70% ←[33m[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 10396346, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=50.800353&mlon=-1.621318←[0m
. 80% . 90% .←[0m
[info] Sorting and writing 0 maneuver overrides...←[0m
[info] done.←[0m
[info] Renumbering turns←[0m
[info] Writing 0 conditional turn penalties...←[0m
[info] Generated 14666821 edge based node segments←[0m
[info] Node-based graph contains 7630589 edges←[0m
[info] Edge-expanded graph ...←[0m
[info]   contains 14162397 edges←[0m
[info] Timing statistics for edge-expanded graph:←[0m
[info] Renumbering edges: 0.155054s←[0m
[info] Generating nodes: 2.13709s←[0m
[info] Generating edges: 12.5739s←[0m
[info] Generating guidance turns ←[0m
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% .←[0m
[info] done.←[0m
[info] Created 114 entry classes and 18233 Bearing Classes←[0m
[info] Handled: 2257 of 31019 lanes: 7.27619 %.←[0m
[info] Assigned 16149017 turn instruction types:←[0m
[info]   new name: 587183 (3.64%)←[0m
[info]   continue: 1881437 (11.65%)←[0m
[info]   turn: 5158831 (31.95%)←[0m
[info]   merge: 12599 (0.08%)←[0m
[info]   on ramp: 5082 (0.03%)←[0m
[info]   off ramp: 7129 (0.04%)←[0m
[info]   fork: 88676 (0.55%)←[0m
[info]   end of road: 3243415 (20.08%)←[0m
[info]   notification: 392 (0.00%)←[0m
[info]   enter roundabout: 40473 (0.25%)←[0m
[info]   enter and exit roundabout: 27 (0.00%)←[0m
[info]   enter rotary: 8194 (0.05%)←[0m
[info]   enter and exit rotary: 5 (0.00%)←[0m
[info]   enter roundabout turn: 15698 (0.10%)←[0m
[info]   enter and exit roundabout turn: 1 (0.00%)←[0m
[info]   (noturn): 1066639 (6.60%)←[0m
[info]   (suppressed): 3864174 (23.93%)←[0m
[info]   roundabout: 15 (0.00%)←[0m
[info]   exit roundabout: 47909 (0.30%)←[0m
[info]   rotary: 13 (0.00%)←[0m
[info]   exit rotary: 9142 (0.06%)←[0m
[info]   exit roundabout turn: 15858 (0.10%)←[0m
[info]   (stay on roundabout): 68296 (0.42%)←[0m
[info]   (sliproad): 27829 (0.17%)←[0m
[info] Assigned 16149017 turn instruction modifiers:←[0m
[info]   uturn: 1160019 (7.18%)←[0m
[info]   sharp right: 240527 (1.49%)←[0m
[info]   right: 4367998 (27.05%)←[0m
[info]   slight right: 468213 (2.90%)←[0m
[info]   straight: 4776697 (29.58%)←[0m
[info]   slight left: 479372 (2.97%)←[0m
[info]   left: 4458195 (27.61%)←[0m
[info]   sharp left: 197996 (1.23%)←[0m
[info] Guidance turn annotations took 218.188s←[0m
[info] Writing Intersection Classification Data←[0m
[info] ok, after 0.072547s←[0m
[info] Writing Turns and Lane Data...←[0m
[info] ok, after 0.051802s←[0m
[info] Saving edge-based node weights to file.←[0m
[info] Done writing. (0.052609)←[0m
[info] Computing strictly connected components ...←[0m
[info] Found 21140 SCC (1 large, 21139 small)←[0m
[info] SCC run took: 0.815969s←[0m
[info] Building r-tree ...←[0m
[info] Constructing r-tree of 14666821 segments build on-top of 14073957 coordinates←[0m
[info] finished r-tree construction in 2.25587 seconds←[0m
[info] Writing edge-based-graph edges       ... ←[0m
[info] ok, after 0.80495s←[0m
[info] Processed 14162397 edges←[0m
[info] Expansion: 51003 nodes/sec and 28209 edges/sec←[0m
[info] To prepare the data for routing, run: ./osrm-contract "great-britain-latest.osrm"←[0m
[info] RAM: peak bytes used: <not implemented on Windows>←[0m

C:\Users\datta\source\repos\WinFormsApp2\WinFormsApp2\bin\Release\netcoreapp3.1>osrm-partition great-britain-latest.osrm
[info] Computing recursive bisection←[0m
[info] Loaded compressed node based graph: 8199846 edges, 14073957 nodes←[0m
[info]  running partition: 128 1.2 0.25 10 1000 # max_cell_size balance boundary cuts small_component_size←[0m
[info] Found 10579716 SCC (1 large, 10579715 small)←[0m
[info] SCC run took: 0.974948s←[0m
[info] Full bisection done in 274.538s←[0m
[info] Loaded node based graph to edge based graph mapping←[0m
[info] Loaded edge based graph for mapping partition ids: 28300190 edges, 7784253 nodes←[0m
[info] Fixed 1264 unconnected nodes←[0m
[info] Edge-based-graph annotation:←[0m
[info]   level 1 #cells 41037 bit size 16←[0m
[info]   level 2 #cells 2843 bit size 12←[0m
[info]   level 3 #cells 184 bit size 8←[0m
[info]   level 4 #cells 7 bit size 3←[0m
[info] Renumbered data in 17.1043 seconds←[0m
[info] MultiLevelPartition constructed in 1.20668 seconds←[0m
[info] CellStorage constructed in 0.919214 seconds←[0m
[info] MLD data writing took 0.673525 seconds←[0m
[info] Cells statistics per level←[0m
[info] Level 1 #cells 41037 #boundary nodes 648246, sources: avg. 10, destinations: avg. 15, entries: 7772624 (62180992 bytes)←[0m
[info] Level 2 #cells 2843 #boundary nodes 108764, sources: avg. 25, destinations: avg. 35, entries: 2981678 (23853424 bytes)←[0m

C:\Users\datta\source\repos\WinFormsApp2\WinFormsApp2\bin\Release\netcoreapp3.1>osrm-customize great-britain-latest.osrm
[info] Loaded edge based graph: 28300190 edges, 7784253 nodes←[0m
[info] Loading partition data took 4.93319 seconds←[0m
[info] Cells customization took 3.15367 seconds←[0m
[info] Cells statistics per level←[0m
[info] Level 1 #cells 41037 #boundary nodes 648246, sources: avg. 10, destinations: avg. 15, entries: 7772624 (62180992 bytes)←[0m
[info] Level 2 #cells 2843 #boundary nodes 108764, sources: avg. 25, destinations: avg. 35, entries: 2981678 (23853424 bytes)←[0m

C:\Users\datta\source\repos\WinFormsApp2\WinFormsApp2\bin\Release\netcoreapp3.1>osrm-routed great-britain-latest.osrm
[info] starting up engines, v5.22.0←[0m
[info] Threads: 16←[0m
[info] IP address: 0.0.0.0←[0m
[info] IP port: 5000←[0m
←[31m[error] [exception] Could not find any metrics for CH in the data. Did you load the right dataset?←[0m

C:\Users\datta\source\repos\WinFormsApp2\WinFormsApp2\bin\Release\netcoreapp3.1>osrm-routed --algorithm=MLD  great-britain-latest.osrm
[info] starting up engines, v5.22.0←[0m
[info] Threads: 16←[0m
[info] IP address: 0.0.0.0←[0m
[info] IP port: 5000←[0m
←[31m[error] [exception] Could not find any metrics for MLD in the data. Did you load the right dataset?←[0m

**Comment by a6datta** [comment]
I think great-britain-latest.osrm.hsgr is missing. 5.16 generates this. May be it's not required in 5.22.

**Comment by a6datta** [comment]
@ssuluh 
Looks like osrm issue. If I prepare for MLD first nothing works, if I prepare for CH first then CH profile works. 
Thanks

**Comment by a6datta** [comment]
Will you be adding nuget package for dot net framework as well in future. Or is it only going to be net core? 

Pls see the image for issue with dot net framework 4.8 and latest osrmnet.
![dotnet](https://user-images.githubusercontent.com/14138235/147394798-28dc0b9a-4cf7-4326-8cb7-e70fa9012c03.png)

For now I have manged to use the nuget package 1.0.0.26 in dot net framework project and it works. 

However, it looks like the library is impractical to use in production environment. 
My current project uses the Route service in parallel from multiple threads. With osrm webservice it works fine. But with osrmnet I get this error
Osrmnet.OsrmException: File "great-britain-latest.osrm.icd" mapping failed: failed opening file: The process cannot access the file because it is being used by another process: iostream stream errorinclude\util/mmap_file.hpp:33
   at Osrmnet.Osrm..ctor(EngineConfig A_0)

My knowledge is limited but in my other projects where I have file operation, I open file for reading without write lock. 

Your help will be much appreciated. 

Thanks

**Comment by ssuluh** [comment]
@a6datta , this library is used in various productions, it looks like your lock issues is due to something else.  Moving forward however, because of limitation of .NET interop and limited osrm windows support, it's getting harder to maintain this library.  At this point you can only run this lib in Windows platform, 64 bit process only (this is verified working).  If you don't want to wrap osrm library directly I would recommend you look into swig or use the osrm webservice directly and have your .net app talk to the webservice.

**Comment by a6datta** [comment]
@ssuluh 
I appreciate your work and thank you for starting this project. 

I could try to re produce the issue on a smaller project, I could be wrong, lets see. 

Secondly my question was not about windows 64 bit. I ran it on a 64 bit application. My question was whether you will release a NuGet package for dot net framework as well or it will only be for dot net core.

**Comment by a6datta** [comment]
@ssuluh Could you please check this sample and tell me what I am doing wrong when you have a few minutes. Thanks

```
public partial class Form1 : Form
    {        
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            GetDistanceAsync();
        }

        private void distanceTaskCallback(Task[] obj)
        {
            foreach (Task<RouteResult> t in obj)
            {
                this.BeginInvoke((Action)(()=>{
                        richTextBox1.Text = Environment.NewLine + t.Result.Code;                    
                }));                
            }            
        }

        private RouteResult GetDistances(Coordinate start, Coordinate end) 
        {
            using (Osrm osrm = new Osrm(new EngineConfig() { StorageConfig = AppDomain.CurrentDomain.BaseDirectory + "great-britain-latest.osrm", Algorithm = Algorithm.CH, UseSharedMemory = false }))
            {
                RouteResult routeResult;
                var result = osrm.Route(new RouteParameters()
                {
                    Coordinates = new List<Coordinate>()
                    {
                        start,
                        end
                    },
                }, out routeResult);
                return routeResult;
            }            
        }
        private async Task GetDistanceAsync() 
        {
            List<Task> taskList = new List<Task>();
            Coordinate start = new Coordinate(51.559510, -0.132860);
            for (double ctr = 0.00001; ctr <= 0.00010; ctr=ctr+0.00001)
            {
                Coordinate end = new Coordinate(51.461280, -0.020340 + ctr);
                taskList.Add(Task.Factory.StartNew(() => GetDistances(start, end)));
            }            
            
            await Task.Factory.ContinueWhenAll(taskList.ToArray(), distanceTaskCallback);
        }
    }  
```

**Comment by ssuluh** [comment]
@a6datta, sorry I wasn't reading your question correctly.  I haven't really investigated how good is the support for c++ cli in dotnet fw, it seems that Microsoft does not see any value in making investment in this area. With everyone prefers running unix container rather than windows, this project become less useful because of this limitation and among other reason that osrm-backend dropped the support for Windows build.

What I suggest you can do is to try to upgrade this project with the latest visual studio. Visual studio always have a built in upgrader for c++ project, you just need to open the sln there.
