### ISSUE TITLE
Sample windows build for osrm-backend 5.22

### ISSUE THREAD

**Issue by swadhin-** [ssuluh/osrmnet#77]
The current version of the project targets osrm-backend 5.22 windows build. To get that one has to go though much pain cause osrm-backend stopped maintaining windows support sometime back. It would be helpful if the working build of osrm-backend 5.22 is referanced from the project. It would make this project more usable

**Comment by ssuluh** [comment]
Hi @swadhin, building osrm-backend is rather out of scope for this project. It's more fruitful to ask how to do windows build in that project as they're more people that may know the topic better than me.

If you just need 5.22 osrm-backend precompiled library, you can clone this project and run local build it will pull prebuild 5.22 that I had long time ago when they still support windows build.  This is the reason this project stays with 5.22.

Have you follow this step from the project ?
https://github.com/Project-OSRM/osrm-backend/wiki/Windows-Compilation

Hope this helps.
