### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by frankvandenbergh** [ssuluh/osrmnet#8]
The data structure of OSRM changes in time and the current osrmnet only works with v5.3. Is it possible to use the version of the OSRM data file and then use the correct libosrm related files?

Or, maybe easier and better, make subprojects within osrmnet per compiled osrm version (with included osrm's compiled exe/dll/lua). Kind of archive with all necessary files within.

**Comment by ssuluh** [comment]
Yes, I think at the minimum include all the tools (exe, lua profile).  This way user don't have to worry about building osrm version.
