### ISSUE TITLE
how to build osrmnet for use to linux

### ISSUE THREAD

**Issue by sadjadesfandiari** [ssuluh/osrmnet#84]
Hi
I created a simple console project and installed the osrmnet nugget package with the following code:

                var testDataPath = Path.Combine("mld", "Orlando.osrm");

                EngineConfig _config = new EngineConfig
                {
                    StorageConfig = testDataPath,
                    UseSharedMemory = false,
                    Algorithm = Algorithm.MLD
                };

                using (var sut = new Osrm(_config))
                {
                    RouteResult routeResult;
                    var result = sut.Route(new RouteParameters
                    {
                        Coordinates = new List<Coordinate>
                        { 
                            new Coordinate(28.479065, -81.463945),
                            new Coordinate(28.598181, -81.207633)
                        }
                    }, out routeResult);

                    Console.WriteLine(routeResult.Code);
                }

And I build and published the program in Windows and it works well in Windows, but it gives the following error in Ubuntu:

Segmentation fault (core dumped)

**Comment by ssuluh** [comment]
Hi @sadjadesfandiari , there is a limitation of Microsoft c++/cli that is the core technology used in this project does not support Unix or MacOS and there's no plan for them to do such a thing the last time I checked. There are other c++ to .net binding out there but that is a huge undertaking to do.
